//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 EzCad3_VS2015.rc 使用
//
#define IDOK2                           2
#define IDC_BUTTON_ISSUE                2
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_ENTBASE              115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDD_DIALOG_PROGRESS             127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDC_TREE_SYSPARAM               129
#define IDR_EzCad3_VS2015TYPE           130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define IDB_BITMAP_SYS                  136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define IDI_ICON_LOCK                   153
#define ID_EXPAND_ALL                   154
#define IDI_ICON_UNLOCK                 154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDD_DIALOG_FLYENCODER           195
#define IDB_MENU_CAMERA                 196
#define IDB_LISTSHOW_OFF                196
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define IDC_CUR_BEZ_MOVE                209
#define ID_VIEW_APPLOOK_VS_2008         210
#define IDR_TOOLBAR_CMDPICK             210
#define IDB_BITMAP_CMDPICK              213
#define IDD_DIALOG_SYSTEMPARAM          214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define IDD_DIALOG_SYS_GENERAL          215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define IDD_DIALOG_SYS_COLOR            217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDD_DIALOG_SYS_WORKSPACE        218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDD_DIALOG_SYS_BACKUP           219
#define IDD_DIALOG_SYS_MOVEROTATE       220
#define IDD_DIALOG_SYS_USER             221
#define IDD_DIALOG_PSW                  222
#define IDD_DIALOG_SYS_LANG             223
#define IDI_ICON_TEXT_SIDE              268
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_PENBOX               310
#define IDC_BUTTON_PEN0                 311
#define IDC_BUTTON_PEN1                 312
#define IDC_BUTTON_PEN2                 313
#define IDC_BUTTON_PEN3                 314
#define IDC_BUTTON_PEN4                 315
#define IDC_BUTTON_PEN5                 316
#define IDC_BUTTON_PEN6                 317
#define IDC_BUTTON_PEN7                 318
#define IDC_BUTTON_PEN8                 319
#define IDC_BUTTON_LISTONOFF            319
#define IDC_MFCPROPERTYGRID2            320
#define IDC_LIST2                       322
#define ID_PEN_APPLYTOPICK              323
#define ID_PEN_LOADPENBOXFROMDEFAULT    324
#define ID_PEN_SETDEFAULTPENSPARAM      325
#define ID_PEN_RESETALLPENS             326
#define IDR_MENU_PEN                    328
#define IDB_BITMAP_MARK_ON              329
#define IDC_STATIC_USER                 331
#define IDC_COMBO_USER                  332
#define IDC_STATIC_PSW                  333
#define IDC_EDIT_PSW                    334
#define IDD_DIALOG_SELUSER              335
#define ID_BAR_PENBOX                   336
#define IDI_ICON_TEXT_L                 338
#define IDI_ICON_TEXT_C                 340
#define IDI_ICON_TEXT_R                 342
#define IDR_TOOLBAR_CMDNODE             373
#define IDR_TOOLBAR_DRAW                374
#define IDR_TOOLBAR_ZOOM3D              375
#define IDC_CUR_ZOOM_WND                378
#define IDR_TOOLBAR_3DFUN               378
#define IDC_CUR_ZOOM_PAN                379
#define IDR_TOOLBAR_ZOOM                379
#define IDD_DIALOG1                     382
#define IDD_DIALOG_REDLIGHT             385
#define IDD_DIALOG_MARKING              386
#define IDC_SPIN1                       387
#define IDC_EDIT1                       398
#define IDC_EDIT_COUNT                  399
#define IDC_EDIT2                       400
#define IDC_EDIT3                       401
#define IDC_EDIT5                       403
#define IDC_STATIC_COUNT                426
#define ID_USER_RUN_LAST_CMD            427
#define IDC_STATIC_ANGLE                427
#define ID_USER_RUN_LAST_CMD2           428
#define IDC_BUTTON_DEL                  433
#define IDC_RADIO_HATCH1                435
#define IDC_RADIO_HATCH2                436
#define IDC_BUTTON_DEL2                 436
#define IDC_RADIO_HATCH3                437
#define IDC_EDIT_LINEANGLE              444
#define IDD_DIALOG_USERPARAM            449
#define IDC_STATIC_UNIT1                450
#define IDC_STATIC_UNIT5                451
#define IDB_BITMAP_ROTATEZ              457
#define IDB_BITMAP_ROTATEX              458
#define IDC_STATIC_UNIT4                459
#define IDB_BITMAP_ROTATEY              459
#define IDC_CHECK_AUTORO2               472
#define IDI_ICON_YFIRST                 490
#define IDI_ICON_XFIRST                 491
#define IDI_ICON_BIDIR                  492
#define IDI_ICON_SINGLEDIR              493
#define IDI_ICON1                       494
#define IDI_ICON_CW                     494
#define IDI_ICON_CCW                    495
#define IDC_CUR_SCALE135                496
#define IDC_CUR_SCALEY                  497
#define IDC_CUR_MOVE                    498
#define IDC_CUR_MOVEADD                 499
#define IDC_CUR_SHEARX                  500
#define IDC_CUR_SHEARY                  501
#define IDC_CUR_SCALE45                 502
#define IDC_CUR_SCALEALL                503
#define IDC_CUR_SCALEX                  504
#define IDC_CUR_CURVE                   505
#define IDC_CUR_NODEPICK                506
#define IDC_CUR_ROTATE                  508
#define IDC_CUR_ROTATECEN               509
#define IDR_MENU1                       510
#define IDR_MENU_PICK                   510
#define IDD_DIALOG2                     511
#define IDD_DIALOG4                     515
#define IDC_CUR_POINT                   517
#define IDC_CURSOR8                     525
#define IDC_CUR_PICK_CURVE              527
#define IDC_CURSOR2                     533
#define IDC_CUR_BEZ_DEL                 535
#define IDC_CUR_BEZ_ADD                 536
#define IDC_CUR_TEXT_PATH               539
#define IDR_MENU_DRAW                   540
#define IDD_DIALOG3                     541
#define IDD_DIALOG6                     544
#define IDC_RADIO10                     551
#define IDC_EDIT_X                      554
#define IDC_EDIT_Y                      555
#define IDC_EDIT_Z                      556
#define IDC_STATIC_UNIT2                557
#define IDC_EDIT_Z2                     557
#define IDC_STATIC_UNIT3                558
#define IDC_STATIC_PREVIEW              566
#define IDC_CHECK_SHOWPRE               567
#define IDC_CHECK_SAVEPRE               568
#define IDC_CHECK_SAVEPRE2              569
#define IDC_CHECK_BINDID                569
#define IDC_LISTCTRL_ENT                570
#define ID_ENTITY_LIST                  571
#define ID_ORDER_MOVEPREV               572
#define ID_ORDER_MOVENEXT               573
#define ID_ORDER_MOVETOP                574
#define ID_ORDER_MOVEBOTTOM             575
#define ID_ORDER_SHOW                   576
#define ID_ORDER_SHOWALL                577
#define ID_ORDER_HIDE                   578
#define IDR_MARK_WND                    579
#define IDD_DIALOG7                     648
#define IDD_DIALOG5                     651
#define IDD_DIALOG8                     658
#define IDD_DIALOG_ENTLIST              658
#define IDR_MENU_ORDER                  660
#define IDB_BITMAP_DRAG_MUL             662
#define IDB_BITMAP_DRAG_ONE             663
#define IDB_BITMAP_SHOWOFF              664
#define IDB_BITMAP_SHOWON               665
#define IDB_BITMAP_ENT0                 666
#define IDI_ICON_STAR1                  666
#define IDB_BITMAP_ENT1                 667
#define IDB_BITMAP_ENT2                 668
#define IDB_BITMAP_ENT3                 669
#define IDB_BITMAP_ENT4                 670
#define IDI_ICON_TEXT_SIDE1             670
#define IDB_BITMAP_ENT5                 671
#define IDI_ICON_TEXT_SAVE1             671
#define IDB_BITMAP_ENT6                 672
#define IDI_ICON_TEXT_R1                672
#define IDB_BITMAP_ENT7                 673
#define IDI_ICON_TEXT_PRJ1              673
#define IDB_BITMAP_ENT8                 674
#define IDI_ICON_TEXT_PATH1             674
#define IDB_BITMAP_ENT9                 675
#define IDI_ICON_TEXT_L1                675
#define IDB_BITMAP_ENT10                676
#define IDI_ICON_TEXT_HATCH1            676
#define IDB_BITMAP_ENT12                677
#define IDI_ICON_TEXT_FORMAT1           677
#define IDB_BITMAP_ENT13                678
#define IDI_ICON_TEXT_C1                678
#define IDB_BITMAP_ENT14                679
#define IDI_ICON_TEXT_BARCODE1          679
#define IDB_BITMAP_ENT15                680
#define IDI_ICON_HATCHLOOP1             680
#define IDI_ICON_LISTON                 680
#define IDB_BITMAP_ENT19                681
#define IDI_ICON_LISTOFF                681
#define IDB_BITMAP_ENT20                682
#define IDB_BITMAP_ENT22                684
#define IDB_BITMAP_ENT23                686
#define IDB_BITMAP_ENT24                687
#define IDB_BITMAP_ENT16                689
#define IDB_BITMAP_ENT21                690
#define IDB_BITMAP_ENTTYPE              691
#define ID_ENTITY_PROP                  692
#define ID_LASERMONITOR                 693
#define ID_DRAW_TOOL                    694
#define IDB_BITMAP_COORANG              719
#define IDB_PNG1                        720
#define IDB_BITMAP2                     721
#define IDB_BITMAP_SHAPE4               721
#define IDB_BITMAP_MARK_OFF             733
#define IDD_DIALOG_LAYERPARAM           735
#define IDD_DIALOG9                     739
#define IDD_DIALOG_LICENSE              739
#define IDC_CURSOR_TRIM                 744
#define IDC_CURSOR_TRIM1                745
#define IDC_CURSOR_INTER                745
#define IDR_TOOLBAR_ALIGN               753
#define IDR_TOOLBAR_DRAW1               754
#define IDR_TOOLBAR_DRAW2               754
#define IDR_TOOLBAR_SYS                 755
#define IDD_DIALOG10                    758
#define IDD_DIALOG_LASERMONITOR         758
#define IDD_DIALOG_LASER_FIBER          760
#define IDB_BITMAP1                     764
#define IDB_BITMAP3                     765
#define IDB_BITMAP_DRAW24               765
#define IDD_DIALOG_MOTIONPANEL          768
#define IDB_PNG2                        770
#define IDB_PNG3                        771
#define IDB_BITMAP4                     772
#define IDC_CURSOR1                     773
#define IDC_CUR_TRIM_NOR                774
#define IDC_CUR_TRIM_ON                 775
#define IDC_CUR_LOCK                    776
#define IDB_BITMAP5                     777
#define IDD_DIALOG_SPLITPARAM           779
#define IDR_MENU_SORT                   791
#define IDD_DIALOG_CAMERASET            794
#define IDD_DIALOG_ISSUE                796
#define IDD_DIALOG_DRAWTOOL             798
#define IDR_TOOLBAR_MARK2               801
#define IDC_BUTTON_APPLYCOPY2           1005
#define IDD_DIALOG_SPLASH               1007
#define IDC_EDIT_SIZEX                  1007
#define IDC_EDIT_SIZEY                  1008
#define IDD_DIALOG_MARK                 1010
#define IDC_BUTTON_APPLY                1010
#define IDC_EDIT_SIZEZ                  1011
#define IDD_DIALOG_LASER_SPI            1015
#define IDD_DIALOG_LASER_SPI1           1017
#define IDD_DIALOG_LASER_QCW            1017
#define IDD_DIALOG_OPENFILE             1018
#define IDD_DIALOG_SELMARKER            1019
#define IDD_DIALOG_LASER_YAG            1020
#define IDC_BUTTON_ADVANCE              1027
#define IDC_BUTTON_PARAMLIB             1028
#define IDB_BITMAP_LAMPSMALL1           1030
#define IDC_STATIC_ENTITY               1030
#define IDB_BITMAP_LAMPSMALL2           1031
#define IDC_STATIC_POS                  1031
#define IDC_STATIC_SIZE                 1032
#define IDB_BITMAP_LAMPSMALL3           1032
#define IDC_EDIT_A                      1033
#define IDC_STATIC_A                    1034
#define IDC_BUTTON_POS                  1035
#define IDC_STATIC_X                    1035
#define IDC_BUTTON_ARRAY                1036
#define IDC_STATIC_Y                    1036
#define IDC_BUTTON_IO                   1037
#define IDC_STATIC_HEIGHT               1039
#define IDC_EDIT_STARTINDEX2            1049
#define IDC_STATIC_FLY                  1052
#define IDC_STATIC_FLYSPEED             1052
#define IDC_STATIC_EDGE                 1056
#define IDC_STATIC_GH2                  1060
#define IDC_STATIC_LASER                1065
#define IDC_STATIC_FIBER                1066
#define IDC_STATIC_DIGITALIO            1067
#define IDC_STATIC_LAMP1                1067
#define IDC_IN0                         1068
#define IDC_STATIC_LAMP2                1068
#define IDC_STATIC_LASER3               1068
#define IDC_STATIC_TEMP                 1068
#define IDC_IN1                         1069
#define IDC_STATIC_LAMP3                1069
#define IDC_IN2                         1070
#define IDC_STATIC_LASER2               1070
#define IDC_IN3                         1071
#define IDC_STATIC_LAMP4                1071
#define IDC_STATIC_PW                   1071
#define IDC_IN4                         1072
#define IDC_STATIC_LAMP5                1072
#define IDC_BUTTON_PW                   1072
#define IDC_IN5                         1073
#define IDC_STATIC_LAMP6                1073
#define IDC_BUTTON_MONITOR              1073
#define IDC_IN6                         1074
#define IDC_IN7                         1075
#define IDC_STATIC_MOTORPANEL           1075
#define IDC_IN8                         1076
#define IDC_STATIC_COOR                 1076
#define IDC_IN9                         1077
#define IDC_BUTTON_PARTHEIGHT           1077
#define IDC_IN10                        1078
#define IDC_STATIC_COOR2                1078
#define IDC_BUTTON_PARTHEIGHT2          1078
#define IDC_BUTTON_FOCUS                1078
#define IDC_IN11                        1079
#define IDC_BUTTON_UP                   1079
#define IDC_IN12                        1080
#define IDC_BUTTON_DOWN                 1080
#define IDC_IN13                        1081
#define IDC_EDIT_STEP                   1081
#define IDC_IN14                        1082
#define IDC_STATIC_FOCUS                1082
#define IDC_IN15                        1083
#define IDC_BUTTON_FOCUS2               1083
#define IDC_BUTTON_HOME                 1083
#define IDC_STATIC_STARTOUT             1084
#define IDC_BUTTON_RESETERR             1084
#define IDC_BUTTON_LEFT                 1084
#define IDC_IN16                        1085
#define IDC_BUTTON_RIGHT                1085
#define IDC_IN17                        1086
#define IDB_BITMAP_CROSS                1086
#define IDC_BUTTON_SPLITSIZE            1086
#define IDC_BUTTON_SPLITPARAM           1086
#define IDC_IN18                        1087
#define IDC_STATIC_SPLITSIZE            1087
#define IDC_BUTTON_DOWNZ                1087
#define IDB_BITMAP_ENT25                1087
#define IDC_IN19                        1088
#define IDC_CHECK_SPLITBYGL             1088
#define IDC_CHECK_SPHEREWARP            1088
#define IDC_BUTTON_UPZ                  1088
#define IDB_BITMAP_ENT26                1088
#define IDC_IN20                        1089
#define IDC_CHECK_KEEPORDER             1089
#define IDC_BUTTON_ORG                  1089
#define IDB_BITMAP_ENT27                1089
#define IDC_IN21                        1090
#define IDC_EDIT_SPLITSIZE              1090
#define IDC_STATIC_FOCUS2               1090
#define IDC_STATIC_ORG                  1090
#define IDB_BITMAP_ENT28                1090
#define IDC_IN22                        1091
#define IDC_COMBO_MODE                  1091
#define IDC_BUTTON_GOORG                1091
#define IDB_LISTSHOW_ON                 1091
#define IDC_IN23                        1092
#define IDC_STATIC_SPLITMODE            1092
#define IDC_STATIC_SPLITPARAM           1092
#define IDB_LISTSHOW_ON1                1092
#define IDC_IN24                        1093
#define IDC_CHECK_KEEPORDER2            1093
#define IDC_CHECK_NOCUTENTITY           1093
#define IDC_BUTTON_ACW                  1093
#define IDC_IN25                        1094
#define IDC_BUTTON_ACCW                 1094
#define IDC_CHECK_REVOLVEWARP           1094
#define IDC_CHECK_REVOLVEWRAP           1094
#define IDC_IN26                        1095
#define IDC_BUTTON_PARTHEIGHT3          1095
#define IDC_BUTTON_PARTDIAMETER         1095
#define IDC_CHECK_NOCUTENTITY2          1095
#define IDC_CHECK_USESPLITBOXCEN        1095
#define IDC_IN27                        1096
#define IDC_BUTTON_HOME2                1096
#define IDC_BUTTON_HANDWHEEL            1096
#define IDC_CHECK_360                   1096
#define IDC_IN28                        1097
#define IDC_EDIT_SPLITSIZEY             1097
#define IDC_STATIC_SPLITPARAM2          1097
#define IDC_STATIC_SPLITPARAMY          1097
#define IDC_IN29                        1098
#define IDC_BUTTON_RIGHT2               1098
#define IDC_BUTTON_PREVIEW              1098
#define IDC_STATIC_SPLITSIZE2           1098
#define IDC_IN30                        1099
#define IDC_IMFILE_FILEINFO             1099
#define IDC_COMBO_MODE2                 1099
#define IDC_BUTTON_AUTOFOCUS            1099
#define IDC_IN31                        1100
#define IDC_IMFILE_SIZE                 1100
#define IDC_STATIC_SPLITMODE2           1100
#define IDC_BUTTON_PREVIEW2             1100
#define IDC_STATIC_STARTOUT2            1101
#define IDC_EDIT_FILESIZE               1101
#define IDC_CHECK_USESPLITBOXCEN2       1101
#define IDC_CHECK_SPLITBYGUIDELINEBOX   1101
#define IDC_IN32                        1102
#define IDC_EDIT_FILEVER                1102
#define IDC_CHECK_DISABLEZ              1102
#define IDC_CHECK_DISABLEAXISA          1102
#define IDC_IN33                        1103
#define IDC_IMFILE_VERSION              1103
#define IDC_CHECK_SPHEREWARP2           1103
#define IDC_CHECK_CYLINDERWARP          1103
#define IDC_IN34                        1104
#define IDC_EDIT_FILEAUTHOR             1104
#define IDC_CHECK_INVERTX               1104
#define IDC_IN35                        1105
#define IDC_IMFILE_AUTHOR               1105
#define IDC_CHECK_INVERTY               1105
#define IDC_IN36                        1106
#define IDC_EDIT_FILEDATE               1106
#define IDC_CHECK_NOCUTENTITY3          1106
#define IDC_CHECK_NOCUTTEXT             1106
#define IDC_IN37                        1107
#define IDC_IMFILE_DATE                 1107
#define IDC_CHECK_SPLITBYGUIDELINEBOX2  1107
#define IDC_CHECK_YFIRST                1107
#define IDC_IN38                        1108
#define IDC_EDIT_FILECOMMENT            1108
#define IDC_IN39                        1109
#define IDC_IMFILE_COMMENT              1109
#define IDC_IN40                        1110
#define IDC_STATIC_SAVETYPE             1110
#define IDC_IN41                        1111
#define IDC_RADIO_SAVEALL               1111
#define IDC_IN42                        1112
#define IDC_RADIO_SAVEPICK              1112
#define IDC_STATIC_MOVE                 1113
#define IDC_IN43                        1113
#define IDC_EDIT_DIST                   1114
#define IDC_IN44                        1114
#define IDC_STATIC_UNIT                 1115
#define IDC_IN45                        1115
#define IDC_IN46                        1116
#define IDC_COMBO_UNIT                  1117
#define IDC_IN47                        1117
#define IDC_RADIO_CONT                  1120
#define IDC_STATIC_LAMP_READY           1123
#define IDC_BUTTON_POWER                1124
#define IDC_STATIC_LAMP_READY2          1125
#define IDC_STATIC_LAMP_POWER           1125
#define IDC_BUTTON_COUNT                1125
#define IDC_BUTTON_ANGLE                1126
#define IDC_LIST_MARKER                 1127
#define IDC_STATIC_YAG                  1128
#define IDC_BUTTON_ENABLE               1129
#define IDC_CHECK_MIRRORX               1130
#define IDC_CHECK_MIRRORY               1131
#define IDC_SLIDER_EXPO                 1132
#define IDC_STATIC_EXPO                 1133
#define IDC_STATIC_EXPO2                1134
#define IDC_EDIT_HEIGHT                 1135
#define IDC_EDIT_W                      1135
#define IDC_STATIC_W                    1136
#define IDC_EDIT_H                      1137
#define IDC_STATIC_H                    1138
#define IDC_SLIDER_EXPO2                1139
#define IDC_EDIT_DESC                   1139
#define IDC_BUTTON_SAVETOFILE           1140
#define IDC_STATIC_DESCRIPTION          1141
#define IDC_BUTTON_SAVETOFILE2          1142
#define IDC_BUTTON_EMAIL                1142
#define IDC_EDIT_MAXTHREAD              1142
#define IDC_SPIN_THREAD                 1143
#define IDC_EDIT_MESHSOL                1144
#define IDC_EDIT_DELAY1                 1144
#define IDC_SPIN_THREAD2                1145
#define IDC_STATIC_DELAY1               1145
#define IDC_STATIC_DELAY2               1146
#define IDC_EDIT_DELAY2                 1147
#define IDC_CHECK_WAITFORINPUT          1148
#define IDC_BUTTON_CAMERAONOFF          1149
#define IDC_STATIC_BMP3                 1157
#define IDC_BUTTON_EXTEND3              1161
#define IDC_STATIC_GRAY                 1163
#define IDC_STATIC_PARAM                1172
#define IDC_STATIC_PASTE_X              1175
#define IDC_STATIC_PASTE_Y              1176
#define IDC_EDIT_PASTEX                 1177
#define IDC_EDIT_PASTEY                 1178
#define IDC_STATIC_GRID                 1181
#define IDC_STATIC_GRIG                 1182
#define IDC_STATIC_RUNSTART             1183
#define IDC_EDIT_STARTRUN               1184
#define IDC_BUTTON_STARTRUN             1185
#define IDC_STATIC_ENDRUN               1186
#define IDC_BUTTON_ENDRUN               1187
#define IDC_STATIC_RUNSTART2            1188
#define IDC_STATIC_MAXTHREAD            1188
#define IDC_BUTTON1                     1189
#define IDC_STATIC_MAXTHREAD2           1189
#define IDC_BUTTON2                     1190
#define IDC_STATIC_MAXTHREAD3           1190
#define IDC_STATIC_MESHSOL              1190
#define IDC_BUTTON3                     1191
#define IDC_CHECK_SHOWGRID              1191
#define IDC_STATIC_BK                   1192
#define IDC_CHECK_SHOWFAST              1192
#define IDC_STATIC_PAPER                1193
#define IDC_CHECK_SHOWDIR               1193
#define IDC_STATIC_GUIDE                1194
#define IDC_STATIC_MAXTHREAD4           1194
#define IDC_STATIC_CLR_PAPER            1195
#define IDC_STATIC_CLR_GUIDE            1196
#define IDC_STATIC_CLR_GRID             1197
#define IDC_STATIC_CLR_BK               1198
#define IDC_CHECK_SHOW                  1199
#define IDC_CHECK_CIRCLE                1200
#define IDC_CHECK_CROSSLINE             1201
#define IDC_STATIC_LEFTCORNER           1202
#define IDC_EDIT_LB_X                   1203
#define IDC_EDIT_LB_Y                   1204
#define IDC_STATIC_LENGTH               1205
#define IDC_STATIC_WIDTH                1206
#define IDC_EDIT_WID                    1207
#define IDC_CHECK_BAK                   1208
#define IDC_EDIT_SAVETIME               1209
#define IDC_STATIC_SAVEBAK              1210
#define IDC_STATIC_EXPLAIN              1211
#define IDC_STATIC_KEY                  1212
#define IDC_STATIC_NUDGESCALE           1213
#define IDC_STATIC_ROTATE               1214
#define IDC_EDIT_NUDGESCALE             1215
#define IDC_STATIC_ORIGINWAY            1216
#define IDC_STATIC_PTNO                 1217
#define IDC_EDIT_PTNUMBER               1218
#define IDC_EDIT_Y1                     1219
#define IDC_STATIC_ANG                  1220
#define IDC_LIST_USER                   1221
#define IDC_CHECK_ENUSER                1222
#define IDC_STATIC_PSW2                 1226
#define IDC_EDIT_NAME                   1227
#define IDC_EDIT_PSW_1                  1228
#define IDC_EDIT_NAME2                  1228
#define IDC_COMBO_LANG                  1229
#define IDC_STATIC_LANGUAGE             1230
#define IDC_STATIC_INFO                 1297
#define IDC_STATIC_INFO2                1298
#define IDC_STATIC_DIAMETER             1300
#define IDC_CHECK_POINTHORI2            1301
#define IDC_EDIT_DELBLK2                1302
#define IDC_COMBO_CHECK2                1302
#define IDC_CHECK_OPTIMIZE2             1353
#define IDC_EDIT_GRID                   1364
#define IDC_EDIT_LEN                    1365
#define IDC_EDIT_ANG                    1366
#define IDC_EDIT_PSW_2                  1367
#define IDC_EDIT_COL2                   1369
#define IDC_EDIT_ENDRUN                 1372
#define IDC_EDIT_X1                     1373
#define IDC_BUTTON_LOCK                 1385
#define IDC_BUTTON_ADD                  1397
#define IDC_BUTTON_MODIFY               1401
#define IDC_BUTTON_F1                   1545
#define IDC_BUTTON_F2                   1546
#define IDC_BUTTON_F3                   1547
#define IDC_CHECK_CONTINUE              1548
#define IDC_CHECK_SELECTED              1549
#define IDC_CHECK_CONTINUE2             1550
#define IDC_CHECK_REDCONTOUR            1550
#define IDC_CHECK_LAYER2                1553
#define IDC_CHECK_OFFLINE               1555
#define IDC_STATIC_PREV                 1569
#define IDC_ABOUT_LAW                   1588
#define IDC_SOFTVERSION                 1589
#define IDC_STATIC_COMPANY              1590
#define IDC_SYSLINK1                    1592
#define IDC_STATIC_1                    1604
#define IDC_STATIC_2                    1605
#define IDC_STATIC_3                    1606
#define IDC_CHECK1                      1610
#define IDC_CHECK2                      1611
#define IDC_CHECK3                      1612
#define IDC_CHECK4                      1613
#define IDC_CHECK5                      1614
#define IDC_CHECK6                      1615
#define IDC_CHECK7                      1616
#define IDC_CHECK8                      1617
#define IDC_STATIC_NAME                 1622
#define IDC_STATIC_NAME2                1623
#define IDC_STATIC_STEP                 1623
#define IDC_STATIC_PART                 1715
#define IDC_EDIT_PART                   1716
#define IDC_STATIC_TOTAL                1717
#define IDC_EDIT_TOTAL                  1718
#define IDC_BUTTON_RESETCOUNT           1719
#define IDC_EDIT_PARTTIME               1720
#define IDC_EDIT_TOTALTIME              1721
#define IDC_BUTTON_RESETCOUNT2          1722
#define IDC_BUTTON_CALC                 1722
#define IDC_EDIT_FILEINDEX              1723
#define IDC_BUTTON_CALC2                1724
#define IDC_BUTTON_GET                  1724
#define IDC_BUTTON_GET2                 1725
#define IDC_BUTTON_FLYSPEED             1725
#define IDC_STATIC_TOTAL2               1726
#define IDC_STATIC_READY                1726
#define IDC_BUTTON_MARK3DBOX            1729
#define IDC_BUTTON_F4                   1729
#define ID_3DVIEW_RENDER                1730
#define ID_3DVIEW_WIRE                  1731
#define ID_3DVIEW_RENDER2               1732
#define ID_VIEW_SNAPGRID                32774
#define ID_VIEW_SNAPGUILDLINE           32775
#define ID_VIEW_SNAPOBJECT              32776
#define ID_DRAW_COOR                    32777
#define ID_DRAW_CLOSE                   32778
#define ID_DRAW_FINISH                  32779
#define ID_ORDER_MOVEPREV32780          32780
#define ID_ORDER_MOVENEXT32781          32781
#define ID_ORDER_MOVETOP32782           32782
#define ID_ORDER_MOVEBOTTOM32783        32783
#define ID_FILE_SYSTEM                  32784
#define ID_EDIT_COMBINE                 32785
#define ID_EDIT_UNCOMBINE               32786
#define ID_EDIT_GROUP                   32787
#define ID_EDIT_UNGROUP                 32788
#define ID_EDIT_ADDLAYER                32789
#define ID_EDIT_DELLAYER                32790
#define ID_EDIT_HATCHENT                32791
#define ID_CMD_PICKALL                  32792
#define ID_CMD_PICKINVERT               32793
#define ID_CMD_PICKDEL                  32794
#define ID_CMD_PICKLOCK                 32795
#define ID_CMD_PICKUNLOCK               32796
#define ID_CMD_PICKUNLOCKALL            32797
#define ID_CMD_PICKCEN                  32798
#define ID_CMD_PICKCENX                 32799
#define ID_CMD_PICKCENY                 32800
#define ID_CMD_PICKMIRRORX              32801
#define ID_CMD_PICKMIRRORY              32802
#define ID_CMD_NODE_ADD                 32803
#define ID_CMD_NODE_DEL                 32804
#define ID_CMD_NODE_UNITE               32805
#define ID_CMD_NODE_SEPA                32806
#define ID_CMD_NODE_TOLINE              32807
#define ID_CMD_NODE_TOARC               32808
#define ID_CMD_NODE_TOBEZ               32809
#define ID_CMD_NODE_SHARP               32810
#define ID_CMD_NODE_SMOOTH              32811
#define ID_CMD_NODE_SYS                 32812
#define ID_CMD_NODE_DIR                 32813
#define ID_CMD_NODE_CLOSE               32814
#define ID_CMD_NODE_ALIGN               32815
#define ID_DRAW_PICK                    32816
#define ID_DRAW_NODE                    32817
#define ID_DRAW_POINT                   32818
#define ID_DRAW_LINE                    32819
#define ID_DRAW_PLINE                   32820
#define ID_DRAW_RECT                    32821
#define ID_DRAW_CIR                     32822
#define ID_DRAW_ELP                     32823
#define ID_DRAW_POLYGON                 32824
#define ID_DRAW_TEXT                    32825
#define ID_DRAW_BARCODE                 32826
#define ID_DRAW_BITMAP                  32827
#define ID_DRAW_VECTORFILE              32828
#define ID_DRAW_TIME                    32829
#define ID_DRAW_INPUT                   32830
#define ID_DRAW_OUTPUT                  32831
#define ID_DRAW_SPIRAL                  32832
#define ID_DRAW_EXTAXIS                 32833
#define ID_3DFUN_SLICE3D                32834
#define ID_MODIFY_ARRAY                 32835
#define ID_MODIFY_ARRAYTEXT             32836
#define ID_VIEW_DRAWBAR                 32837
#define ID_VIEW_ZOOM                    32838
#define ID_VIEW_ZOOM3D                  32839
#define ID_VIEW_ENTLIST                 32840
#define ID_VIEW_ENTPROP                 32841
#define ID_VIEW_MARKPARAM               32842
#define ID_VIEW_MARKPANEL               32843
#define ID_VIEW_SHOWRULER               32844
#define ID_VIEW_SHOWGRID                32845
#define ID_VIEW_SANPGRID                32846
#define ID_ZOOM_WND                     32847
#define ID_ZOOM_PAN                     32848
#define ID_ZOOM_IN                      32849
#define ID_ZOOM_OUT                     32850
#define ID_ZOOM_ALL                     32851
#define ID_ZOOM_PICK                    32852
#define ID_ZOOM_WORKSPACE               32853
#define ID_BUTTON2                      32865
#define ID_BUTTON32876                  32876
#define ID_MODIFY_ROTATE                32882
#define ID_PICK_ROTATE                  32884
#define ID_MODIFY_OFFSETCURVE           32885
#define ID_LASRER                       32886
#define ID_LASRER_MATERIALPROCESS       32887
#define ID_3DFUN_BASESHAPE              32888
#define ID_BUTTON32889                  32889
#define ID_3DFUN_BMPTOMESH              32889
#define ID_BUTTON32890                  32890
#define ID_MODIFY_DISTORTION            32891
#define ID_DISTORTION_WELD              32892
#define ID_DISTORTION_TRIM              32893
#define ID_DISTORTION_INTERSECT         32894
#define ID_MODIFY_TOCURVE               32895
#define ID_PEN                          32896
#define ID_PEN_APPLYTOPICK32897         32897
#define ID_FILE_PROJECTPARAM            32898
#define ID_MODIFY_ALIGN                 32899
#define ID_ZOOM_3D_ISO                  32902
#define ID_3DFUN_RUN                    32903
#define ID_ZOOM_3D_UP                   32904
#define ID_ZOOM_3D_DN                   32905
#define ID_ZOOM_3D_LEFT                 32906
#define ID_ZOOM_3D_RIGHT                32907
#define ID_ZOOM_3D_FR                   32908
#define ID_ZOOM_3D_BACK                 32909
#define ID_3DVIEW_HIDEMESH              32920
#define ID_3DFUN_MESH3D                 32925
#define ID_3DFUN_SLICEMESH              32926
#define ID_3DFUN_ROTATEMESH             32927
#define ID_3DFUN_MOVEMESH               32928
#define ID_3DFUN_PRJ                    32929
#define ID_ALIGN_LEFT                   32930
#define ID_ALIGN_HCENTER                32931
#define ID_ALIGN_RIGHT                  32932
#define ID_ALIGN_TOP                    32933
#define ID_ALIGN_VCENTER                32934
#define ID_ALIGN_BOTTOM                 32935
#define ID_ALIGN_CENTER                 32936
#define ID_VIEW_ALIGN                   32949
#define ID_BUTTON32950                  32950
#define ID_3DFUN_FREEPAINT              32950
#define ID_VIEW_LASERMONITOR            32951
#define ID_LASRER_LASERMONITOR          32952
#define ID_PICK_BYPEN                   32954
#define ID_PICK_MOVETOINDEX             32956
#define ID_ORDER_MOVEINDEX              32957
#define ID_DRAW_AXIS                    32958
#define ID_MODIFY_TRIM                  32959
#define ID_MODIFY_CURVEEDIT             32960
#define ID_CURVEEDIT_AUTOCONNECT        32961
#define ID_CURVEEDIT_BREADCROSSPOINT    32962
#define ID_EDIT_UNGROUPTEXT             32963
#define ID_FILE_MACHINEPARAMETER        32964
#define ID_DRAW_ENCODERDISTANCE         32965
#define ID_DRAW_INDEX                   32966
#define ID_DRAW_CCD                     32967
#define ID_DRAW_INPUTJUMP               32968
#define ID_3DVIEW_RENDERLINE            32970
#define ID_VIEW_SNAPMESHVERTEX          32971
#define ID_MODIFY_MESHEDIT              32972
#define ID_MESHEDIT_MERGECLOSEVERTICES  32973
#define ID_MODIFY_RESORT                32974
#define ID_RESORT_SORTBYX               32975
#define ID_RESORT_SORTBYY               32976
#define ID_RESORT_SORTREVERSE           32977
#define ID_RESORT_FINISH                32978
#define ID_BUTTON32979                  32979
#define ID_MODIFY_CURVETOPOINTS         32981
#define ID_DRAW_GUILDLINE               32982
#define ID_DRAW_GUIDELINEBOX            32983
#define ID_TEST_BUTTON3                 32985
#define ID_TEST_RED                     32986
#define ID_TOOLBAR_MARK3                32987
#define ID_TOOLBAR_MARK4                32988
#define ID_TOOLBAR_RED                  32989
#define ID_DRAW_BARCODE1                32990
#define ID_DRAW_BARCODE2                32991
#define ID_DRAW_BARCODE3                32992

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        805
#define _APS_NEXT_COMMAND_VALUE         32993
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
